### PR TITLE
Bug Correction and Improvment

### PR DESCRIPTION
**Pull request by anildalar**
Bug Correction and Improvment

### CODE REVIEW

**Comment by ugoviti** [comment]
Hi,

why I must include the attached changes?

closing for now

Kind regards

**Comment by anildalar** [comment]
The above changes are working perfectly with a Separate small affordable VPS Server.
The 3rd Senaria I am using for my Company

image

**Comment by anildalar** [comment]
You can refer to this
https://docs.google.com/presentation/d/1WExEhwFnAX_9ESyWyQDyh4UCFruRDiivsy-BoIF1dlY/edit?usp=sharing

**Comment by ugoviti** [comment]
The attached PR include the following modifications: https://github.com/ugoviti/izpbx/pull/78/commits/fa4fe8ef699c25d98324dc202174b496118f3e4a

As I can see, there are the following problems:

- you included .env.swp in the commit
- you deleted default.env
- changed some internal config of compose.yml (if you want override these config use the compose.override.yml)
- phpmyadmin is already included in the main izpbx image

am I missing something?

Kind regards

**Pull request closed without merging**
